security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticateurAuthenticator
            logout:
                path: app_logout
                target: app_home         # ✅ Redirige a inicio después de logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/reservation$, roles: ROLE_ADMIN }

        - { path: ^/reservation/mes-reservations, roles: ROLE_CLIENT }
        - { path: ^/reservation/new, roles: ROLE_CLIENT }
        - { path: ^/reservation/\d+/edit, roles: [ROLE_CLIENT, ROLE_ADMIN] }
        - { path: ^/reservation/\d+/delete, roles: [ROLE_CLIENT, ROLE_ADMIN] }
        - { path: ^/reservation/\d+, roles: [ROLE_CLIENT, ROLE_ADMIN] }

        - { path: ^/chambre/new, roles: ROLE_ADMIN }
        - { path: ^/chambre/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/chambre/\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/utilisateur, roles: ROLE_ADMIN }
        - { path: ^/commentaire/admin, roles: ROLE_ADMIN }

        - { path: ^/commentaire/new, roles: ROLE_CLIENT }
        - { path: ^/commentaire/\d+/edit, roles: [ROLE_CLIENT, ROLE_ADMIN] }
        - { path: ^/commentaire/\d+/delete, roles: [ROLE_CLIENT, ROLE_ADMIN] }
        - { path: ^/commentaire/\d+$, roles: [ROLE_CLIENT, ROLE_ADMIN] }

        - { path: ^/chambre, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10